//! JavaScript/TypeScript binding generation from host-neutral
//! `InterfaceMetadata` (WASM.10/WASM.11). The emitted JS is also the browser
//! host runtime: it provides the WASI shim (`fd_write`/`proc_exit`) the module
//! imports.
#![allow(clippy::match_same_arms)]
use std::fmt::Write as _;

use vut_mir::{Program, SymbolId};

use super::layout::wasm_signature;
use wasm_encoder::ValType;

/// Returns `(app.js, app.d.ts)` for the compiled program.
#[must_use]
pub fn generate(program: &Program, entry: SymbolId) -> (String, String) {
    let js = JS_LOADER.to_owned();
    let mut dts = String::from(
        "// Generated by Vut. Do not edit.\n\
         export interface VutExports {\n  memory: WebAssembly.Memory;\n",
    );
    for function in &program.functions {
        let (params, result) = wasm_signature(&program.layouts, function);
        let params = params
            .iter()
            .enumerate()
            .map(|(index, ty)| format!("arg{index}: {}", ts_type(*ty)))
            .collect::<Vec<_>>()
            .join(", ");
        let result = result.map_or_else(|| "void".to_owned(), ts_type);
        let _ = writeln!(dts, "  vut_fn_{}({params}): {result};", function.symbol.0);
    }
    let _ = entry;
    dts.push_str(
        "  _start(): void;\n}\n\
         export declare function instantiate(source: BufferSource): Promise<VutExports>;\n\
         export declare function load(url: string | URL): Promise<VutExports>;\n",
    );
    (js, dts)
}

fn ts_type(ty: ValType) -> String {
    match ty {
        ValType::I32 => "number".to_owned(),
        ValType::I64 => "bigint".to_owned(),
        ValType::F32 | ValType::F64 => "number".to_owned(),
        other => format!("{other:?}"),
    }
}

const JS_LOADER: &str = r#"// Generated by Vut. Browser/host-neutral WASM loader with a WASI shim.
// The module imports `wasi_snapshot_preview1.fd_write` (used by print/out) and
// optionally `proc_exit`; this shim routes them to the host console.
const __decoder = new TextDecoder();
let __memory = null;

export function hostImports() {
  return {
    wasi_snapshot_preview1: {
      fd_write(_fd, iovs, iovsLen, nwritten) {
        const view = new DataView(__memory.buffer);
        let text = "";
        for (let i = 0; i < iovsLen; i++) {
          const base = iovs + i * 8;
          const ptr = view.getUint32(base, true);
          const len = view.getUint32(base + 4, true);
          text += __decoder.decode(new Uint8Array(__memory.buffer, ptr, len));
        }
        console.log(text.replace(/\n$/, ""));
        if (nwritten) view.setUint32(nwritten, text.length, true);
        return 0;
      },
      proc_exit(code) {
        throw new Error("vut: proc_exit(" + code + ")");
      },
    },
  };
}

export async function instantiate(source) {
  const module = await WebAssembly.compile(source);
  const instance = await WebAssembly.instantiate(module, hostImports());
  __memory = instance.exports.memory;
  return instance.exports;
}

export async function load(url) {
  const response = await fetch(url);
  return instantiate(await response.arrayBuffer());
}
"#;
