[package]
name = "vut-fuzz"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
vut-lexer = { path = "../vut-lexer" }
vut-parser = { path = "../vut-parser" }
vut-source = { path = "../vut-source" }
vut-tooling = { path = "../vut-tooling" }

[lints]
workspace = true
