//! Package publication command surface.
//!
//! ```text
//! vpm publish [registry] [--dry-run]
//! ```
//!
//! With no registry argument, publication targets the default registry
//! (`duongonix/vpm`); an `owner/repository` argument selects a self-hosted
//! registry. The package name is taken from `[package].name`, never from the
//! command line.
//!
//! Publication is a review-gated, source-only flow: VPM validates the package
//! and submits a change for review. Trusted CI then builds per-target native
//! artifacts and generates `native-artifacts.toml`. Publishers must not submit
//! prebuilt binaries.

mod github;

use crate::Manifest;
use std::{collections::BTreeMap, path::Path};

pub use github::GitHubPublisher;

/// A validated package ready to be submitted to a registry.
pub struct PublishPlan {
    pub owner: String,
    pub repository: String,
    pub registry: String,
    pub package: String,
    pub version: String,
    /// Files relative to the package root.
    pub files: BTreeMap<String, Vec<u8>>,
}

/// Outcome reported to the CLI.
pub struct PublishReport {
    pub package: String,
    pub version: String,
    pub registry: String,
    pub files: usize,
    pub dry_run: bool,
}

/// Provider-abstract submission mechanism.
pub trait Publisher {
    fn submit(&self, plan: &PublishPlan) -> Result<(), Box<dyn std::error::Error>>;
}

/// Validates the current package and submits it (unless `dry_run`).
pub fn publish(
    root: &Path,
    registry: Option<&str>,
    dry_run: bool,
) -> Result<PublishReport, Box<dyn std::error::Error>> {
    let plan = plan(root, registry)?;
    if dry_run {
        return Ok(report(&plan, true));
    }
    GitHubPublisher::from_env()?.submit(&plan)?;
    Ok(report(&plan, false))
}

/// Validates and submits with an explicit publisher (used by tests).
#[cfg(test)]
pub fn publish_with<P: Publisher>(
    publisher: &P,
    root: &Path,
    registry: Option<&str>,
    dry_run: bool,
) -> Result<PublishReport, Box<dyn std::error::Error>> {
    let plan = plan(root, registry)?;
    if !dry_run {
        publisher.submit(&plan)?;
    }
    Ok(report(&plan, dry_run))
}

/// Validates a package and builds the submission plan without any network use.
pub fn plan(
    root: &Path,
    registry: Option<&str>,
) -> Result<PublishPlan, Box<dyn std::error::Error>> {
    let manifest = Manifest::read(root)?;
    if !manifest.native.libraries.is_empty() {
        return Err(
            "registry packages must not declare `[native] libraries`; publish native source with `[native] build`"
                .into(),
        );
    }
    let files = collect_files(root)?;
    let has_library = files.contains_key("src/mod.vut");
    if !has_library && manifest.bin.is_empty() {
        return Err("package has neither a `src/mod.vut` library nor any `[[bin]]` entry".into());
    }
    if files.contains_key(crate::artifact::FILE) {
        return Err(
            "publish must not include `native-artifacts.toml`; it is generated by trusted CI"
                .into(),
        );
    }
    if let Some(build) = &manifest.native.build {
        let bytes = files.get(build).ok_or_else(|| {
            format!("declared native build `{build}` is missing from the package")
        })?;
        let text = std::str::from_utf8(bytes)
            .map_err(|_| "native build file is not valid UTF-8".to_owned())?;
        crate::native::NativeBuild::parse(text)?;
    }
    if let Some(path) = files
        .keys()
        .find(|path| crate::native::is_prebuilt_artifact(path))
    {
        return Err(format!("must not publish prebuilt native artifact `{path}`").into());
    }
    let (owner, repository) = registry_target(registry)?;
    Ok(PublishPlan {
        registry: format!("{owner}/{repository}"),
        owner,
        repository,
        package: manifest.package.name,
        version: manifest.package.version,
        files,
    })
}

fn report(plan: &PublishPlan, dry_run: bool) -> PublishReport {
    PublishReport {
        package: plan.package.clone(),
        version: plan.version.clone(),
        registry: plan.registry.clone(),
        files: plan.files.len(),
        dry_run,
    }
}

/// Resolves the target registry: the official one by default, or `owner/repo`.
fn registry_target(registry: Option<&str>) -> Result<(String, String), String> {
    let Some(value) = registry else {
        return Ok(("duongonix".into(), "vpm".into()));
    };
    let parts: Vec<_> = value.split('/').collect();
    if parts.len() != 2
        || parts
            .iter()
            .any(|part| part.is_empty() || *part == "." || *part == "..")
    {
        return Err(format!(
            "invalid registry `{value}`; expected owner/repository"
        ));
    }
    Ok((parts[0].to_owned(), parts[1].to_owned()))
}

fn collect_files(root: &Path) -> Result<BTreeMap<String, Vec<u8>>, Box<dyn std::error::Error>> {
    let mut files = BTreeMap::new();
    visit(root, root, &mut files)?;
    Ok(files)
}

fn visit(
    root: &Path,
    current: &Path,
    files: &mut BTreeMap<String, Vec<u8>>,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut entries = std::fs::read_dir(current)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(std::fs::DirEntry::file_name);
    for entry in entries {
        let path = entry.path();
        let relative = path
            .strip_prefix(root)
            .map_err(|_| "package path escaped its root")?;
        let key = relative.to_string_lossy().replace('\\', "/");
        if path.is_dir() {
            if is_ignored_dir(&key) {
                continue;
            }
            visit(root, &path, files)?;
        } else if !is_ignored_file(&key) {
            files.insert(key, std::fs::read(&path)?);
        }
    }
    Ok(())
}

fn is_ignored_dir(relative: &str) -> bool {
    matches!(
        relative,
        ".git" | "build" | ".vpm" | ".vut-cache" | "target"
    )
}

fn is_ignored_file(relative: &str) -> bool {
    matches!(relative, "vpm.lock" | ".gitignore")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    struct Recording {
        submitted: std::cell::RefCell<usize>,
    }
    impl Publisher for Recording {
        fn submit(&self, _plan: &PublishPlan) -> Result<(), Box<dyn std::error::Error>> {
            *self.submitted.borrow_mut() += 1;
            Ok(())
        }
    }

    fn package(name: &str, extra: &[(&str, &str)]) -> PathBuf {
        use std::sync::atomic::{AtomicUsize, Ordering};
        static COUNTER: AtomicUsize = AtomicUsize::new(0);
        let nonce = COUNTER.fetch_add(1, Ordering::Relaxed);
        let root =
            std::env::temp_dir().join(format!("vpm-publish-{name}-{}-{nonce}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("src/bin")).unwrap();
        std::fs::write(
            root.join("vpm.toml"),
            format!(
                "[package]\nname = '{name}'\nversion = '1.0.0'\n\n[[bin]]\nname = '{name}'\npath = 'src/bin/{name}.vut'\n"
            ),
        )
        .unwrap();
        std::fs::write(
            root.join(format!("src/bin/{name}.vut")),
            "fn main():\n  out(\"hi\")\n",
        )
        .unwrap();
        for (path, content) in extra {
            let full = root.join(path);
            std::fs::create_dir_all(full.parent().unwrap()).unwrap();
            std::fs::write(full, content).unwrap();
        }
        root
    }

    #[test]
    fn dry_run_validates_without_submitting() {
        let root = package("math", &[]);
        let publisher = Recording {
            submitted: std::cell::RefCell::new(0),
        };
        let report = publish_with(&publisher, &root, None, true).unwrap();
        assert!(report.dry_run);
        assert_eq!(report.registry, "duongonix/vpm");
        assert_eq!(*publisher.submitted.borrow(), 0);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn submits_once_to_a_self_hosted_registry() {
        let root = package("math", &[]);
        let publisher = Recording {
            submitted: std::cell::RefCell::new(0),
        };
        let report = publish_with(&publisher, &root, Some("alice/vut-packages"), false).unwrap();
        assert_eq!(report.registry, "alice/vut-packages");
        assert_eq!(*publisher.submitted.borrow(), 1);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn rejects_prebuilt_artifacts_and_generated_metadata() {
        let binary = package("math", &[("native/math.lib", "binary")]);
        assert!(plan(&binary, None).is_err());
        std::fs::remove_dir_all(binary).unwrap();

        let generated = package("math", &[(crate::artifact::FILE, "format = 1\n")]);
        assert!(plan(&generated, None).is_err());
        std::fs::remove_dir_all(generated).unwrap();
    }

    #[test]
    fn rejects_invalid_registry_and_empty_package() {
        let root = package("math", &[]);
        assert!(plan(&root, Some("not-a-registry")).is_err());
        std::fs::remove_dir_all(root).unwrap();

        let empty = std::env::temp_dir().join(format!("vpm-publish-empty-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&empty);
        std::fs::create_dir_all(&empty).unwrap();
        std::fs::write(
            empty.join("vpm.toml"),
            "[package]\nname = 'math'\nversion = '1.0.0'\n",
        )
        .unwrap();
        std::fs::create_dir_all(empty.join("src")).unwrap();
        std::fs::write(empty.join("src/helper.vut"), "fn h() -> int:\n  1\n").unwrap();
        assert!(plan(&empty, None).is_err());
        std::fs::remove_dir_all(empty).unwrap();
    }
}
